[package]
name = "tuf"
version = "0.0.3"
authors = [ "heartsucker <heartsucker@autistici.org>" ]
description = "Library for The Update Framework (TUF)"
homepage = "https://github.com/heartsucker/rust-tuf"
repository = "https://github.com/heartsucker/rust-tuf"
documentation = "https://docs.rs/tuf"
readme = "README.md"
license = "MIT"
keywords = [ "security" ]
categories = [ "cryptography" ]

[badges]
travis-ci = { repository = "heartsucker/rust-tuf", branch = "master" }
appveyor = { repository = "heartsucker/rust-tuf", branch = "master", service = "github" }

[lib]
name = "tuf"
path = "./src/lib.rs"

[[bin]]
name = "tuf"
path = "./src/main.rs"
doc = false
required-features = [ "cli" ]

[features]
cli = [ "clap" ]

[dependencies]
chrono = { version = "0.3.1", features = [ "serde" ] }
clap = { version = "2.23", optional = true }
data-encoding = "2.0.0-rc.1"
env_logger = "0.4.2"
hyper = "0.10.10"
itoa = "0.3"
log = "0.3"
ring = "0.9.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
url = "1.4"
untrusted = "0.5"
uuid = { version = "0.5", features = [ "v4" ] }

[dev-dependencies]
tempdir = "0.3"
